version: '3.9'

services:
  odoo:
    image: "{{ odoo_image }}"
    container_name: "{{ odoo_container_name }}"
    ports:
      - "{{ odoo_port }}:8069"
    environment:
      - HOST={{ odoo_db_host }}
      - PORT={{ odoo_db_port }}
      - USER={{ odoo_db_user }}
      - PASSWORD={{ odoo_db_password }}
      - ODOO_URL={{ odoo_url }}
    volumes:
      - "{{ odoo_volume_path }}:/var/lib/odoo"
    networks:
      - "{{ docker_network_name }}"

  db:
    image: postgres:14
    container_name: "{{ odoo_db_container_name }}"
    environment:
      - POSTGRES_USER={{ odoo_db_user }}
      - POSTGRES_PASSWORD={{ odoo_db_password }}
      - POSTGRES_DB=odoo
    volumes:
      - "{{ odoo_db_volume_path }}:/var/lib/postgresql/data"
    networks:
      - "{{ docker_network_name }}"

networks:
  "{{ docker_network_name }}":
    driver: bridge

volumes:
  "{{ odoo_volume_name }}":
  "{{ odoo_db_volume_name }}":
