# odoo-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: icgroups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
        - name: postgres
          image: postgres:12
          env:
            - name: POSTGRES_DB
              value: odoo
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-db-secret
                  key: password
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-pvc
