version: '3'
services:
  odoo:
    image: odoo:latest
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password
    volumes:
      - odoo-data:/var/lib/odoo
    networks:
      - odoo-net
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

volumes:
  odoo-data:
  db-data:

networks:
  odoo-net:
    driver: bridge
